<a href="https://colab.research.google.com/github/uvictoli/Machine_Learning/blob/main/Lv4/Lv4_%EC%A0%84%EC%B2%98%EB%A6%AC_%EB%B3%B5%EC%8A%B5_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [‚Ü©Ô∏è Î¶¨Ïä§Ìä∏Î°ú ÎèåÏïÑÍ∞ÄÍ∏∞](https://dacon.io/competitions/open/235698/overview/description)

# ÏÖÄÏùÑ Ïã§ÌñâÌï† Îïå ÌåùÏóÖÏù¥ Îú®Î©¥ `Î¨¥ÏãúÌïòÍ≥† Í≥ÑÏÜçÌïòÍ∏∞` Î•º ÎàåÎü¨Ï£ºÏÑ∏Ïöî

Í∏∞Ï°¥ ÎÇ¥Ïö©Í≥º ÏÉÅÏù¥Ìïú Î∂ÄÎ∂ÑÏù¥ ÏûàÏñ¥ Ï£ºÏÑùÏúºÎ°ú Î¨∏Ï†úÎ•º Ï†úÏ∂úÌïòÎäî Í≤ÉÏóê ÌïúÍ≥ÑÍ∞Ä ÏûàÍ∏∞ÎïåÎ¨∏Ïóê,   
Ïù¥Î≤àÏãúÍ∞ÑÏóêÎäî Í≤åÏãúÍ∏ÄÏùò ÏΩîÎìúÎ•º Î≥¥Î©∞ ÌïÑÏÇ¨ÌïòÎäî ÏãúÍ∞ÑÏùÑ Í∞ñÎèÑÎ°ù ÌïòÍ≤†ÏäµÎãàÎã§.

## Îç∞Ïù¥ÌÑ∞ Îã§Ïö¥Î°úÎìú
---
ÏïÑÎûò ÏÖÄÏùÑ Ïã§ÌñâÏãúÏºú Îç∞Ïù¥ÌÑ∞Î•º colab Ïóê Î∂àÎü¨ÏòµÎãàÎã§.
ÏÖÄ Ïã§ÌñâÏùÄ Ctrl + Enter Î•º Ïù¥Ïö©Ìï¥ Ïã§ÌñâÏãúÌÇ¨ Ïàò ÏûàÏäµÎãàÎã§.

In [1]:
# Îç∞Ïù¥ÌÑ∞ Îã§Ïö¥Î°úÎìú ÎßÅÌÅ¨Î°ú Îç∞Ïù¥ÌÑ∞Î•º ÏΩîÎû©Ïóê Î∂àÎü¨ÏòµÎãàÎã§.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2022-02-10 04:04:39--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2022-02-10 04:04:39--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 142.250.97.100, 142.250.97.102, 142.250.97.113, ...
Connecting to drive.google.com (drive.google.com)|142.250.97.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fq2b5ts5qde0k8j4ot4665ip3vfglu1f/1644465825000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download [following]
Warning: wildcards not supported in HTTP.
--2022-02-10 04:04:39--  https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fq2b5ts5qde0k8j4ot4665ip3vfglu1f/1644465825000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download
Resolving doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)... 173.194.214.132, 2607:f8b0:400c:c0b::84
Connecting to doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)|173.194.214.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137694 (134K) [application/zip]
Saving to: ‚Äò3i4n1QB‚Äô

3i4n1QB             100%[===================>] 134.47K  --.-KB/s    in 0.002s

2022-02-10 04:04:40 (77.0 MB/s) - ‚Äò3i4n1QB‚Äô saved [137694/137694]

In [2]:
# ÎùºÏù¥Î∏åÎü¨Î¶¨ Î∞è Îç∞Ïù¥ÌÑ∞ Î∂àÎü¨Ïò§Í∏∞
import pandas as pd

train = pd.read_csv('data/train.csv')

## üëã Ïã§Ïäµ
---

In [3]:
# train Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44     10.2  white
1      1        5            8.8  ...       0.59      9.5    red
2      2        5            7.9  ...       0.52     10.9  white
3      3        6            7.0  ...       0.50     10.8  white
4      4        6            7.8  ...       0.43     10.9  white

[5 rows x 14 columns]

In [5]:
 # train Îç∞Ïù¥ÌÑ∞Ïùò alcohol Î≥ÄÏàòÎ•º Íµ¨Í∞ÑÏù¥ 5Í∞úÏù∏ Î≤îÏ£ºÌòï Î≥ÄÏàòÎ°ú Î≥ÄÌôò
 train['alcohol'] = pd.cut(train.alcohol, 5, labels = False)

In [6]:
# Î≥ÄÌôò ÌõÑ Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44        1  white
1      1        5            8.8  ...       0.59        1    red
2      2        5            7.9  ...       0.52        2  white
3      3        6            7.0  ...       0.50        2  white
4      4        6            7.8  ...       0.43        2  white

[5 rows x 14 columns]

## Ï†ïÎãµ

In [8]:
# train Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44        1  white
1      1        5            8.8  ...       0.59        1    red
2      2        5            7.9  ...       0.52        2  white
3      3        6            7.0  ...       0.50        2  white
4      4        6            7.8  ...       0.43        2  white

[5 rows x 14 columns]

In [10]:
 # train Îç∞Ïù¥ÌÑ∞Ïùò alcohol Î≥ÄÏàòÎ•º Íµ¨Í∞ÑÏù¥ 5Í∞úÏù∏ Î≤îÏ£ºÌòï Î≥ÄÏàòÎ°ú Î≥ÄÌôò
 train['alcohol'] = pd.cut(train.alcohol, 5,labels=False)

In [11]:
# Î≥ÄÌôò ÌõÑ Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44        1  white
1      1        5            8.8  ...       0.59        1    red
2      2        5            7.9  ...       0.52        2  white
3      3        6            7.0  ...       0.50        2  white
4      4        6            7.8  ...       0.43        2  white

[5 rows x 14 columns]

## üëã Ïã§Ïäµ
---
1. train Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò
2. Î™®Îç∏ ÌïôÏäµ (Decision Tree)
3. test Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò
4. Ï∂îÎ°†
5. Ï†ïÎãµ ÌååÏùº ÏÉùÏÑ±

In [12]:
# ÎùºÏù¥Î∏åÎü¨Î¶¨ Î∞è Îç∞Ïù¥ÌÑ∞ Î∂àÎü¨Ïò§Í∏∞
import pandas as pd

# PolynomialFeatures ÎùºÏù¥Î∏åÎü¨Î¶¨ Ìò∏Ï∂ú
from sklearn.preprocessing import PolynomialFeatures

# Îç∞Ïù¥ÌÑ∞ Î∂àÎü¨Ïò§Í∏∞
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

# Î≤îÏ£ºÌòï Î≥ÄÏàò Ï†úÍ±∞
train.drop('type', axis = 1,inplace = True)
test.drop('type', axis = 1,inplace = True)

# index Î≥ÄÏàò Ï†úÍ±∞

train.drop('index', axis = 1,inplace = True)
test.drop('index', axis = 1,inplace = True)

In [13]:
# Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   quality  fixed acidity  volatile acidity  ...    pH  sulphates  alcohol
0        5            5.6             0.695  ...  3.44       0.44     10.2
1        5            8.8             0.610  ...  3.19       0.59      9.5
2        5            7.9             0.210  ...  3.05       0.52     10.9
3        6            7.0             0.210  ...  3.26       0.50     10.8
4        6            7.8             0.400  ...  3.04       0.43     10.9

[5 rows x 12 columns]

In [16]:
 # train Îç∞Ïù¥ÌÑ∞Î•º PolynomialFeatures Î•º Ïù¥Ïö©ÌïòÏó¨ Î≥ÄÌôò
poly_features = PolynomialFeatures(degree = 2)

df = train.drop('quality',axis = 1)
df_poly = poly_features.fit_transform(df)
df_poly = pd.DataFrame(df_poly)

In [17]:
# DecisionTreeClassifier Î™®Îç∏ÏùÑ Î≥ÄÌôòÎêú train Îç∞Ïù¥ÌÑ∞Î°ú ÌïôÏäµ

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(df_poly,train['quality'])

DecisionTreeClassifier()

In [18]:
# test Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò
poly_features = PolynomialFeatures(degree = 2) 

test_poly = poly_features.fit_transform(test)
test_poly = pd.DataFrame(test_poly)

In [19]:
# Í≤∞Í¥èÍ∞í Ï∂îÎ°†
pred = model.predict(test_poly)

In [20]:
# Ï†ïÎãµ ÌååÏùº ÏÉùÏÑ±
submission = pd.read_csv('data/sample_submission.csv')
submission['quality'] = pred
submission.to_csv('poly.csv',index = False)

## Ï†ïÎãµ
---

In [21]:
 # train Îç∞Ïù¥ÌÑ∞Î•º PolynomialFeatures Î•º Ïù¥Ïö©ÌïòÏó¨ Î≥ÄÌôò
 
poly_features = PolynomialFeatures(degree=2) # Ï∞®ÏõêÏùÄ 2Î°ú ÏÑ§Ï†ï

# ÏôÄÏù∏ ÌíàÏßà Í∏∞Ï§ÄÏù∏ quality Î≥ÄÏàòÎ•º Ï†úÏô∏Ìïú ÎÇòÎ®∏ÏßÄ Î≥ÄÏàòÎ•º Ìè¨Ìï®Ìïú Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò.
df = train.drop('quality',axis = 1)
df_poly = poly_features.fit_transform(df) # fit_transform Î©îÏÜåÎìúÎ•º ÌÜµÌï¥ Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò
df_poly = pd.DataFrame(df_poly) # PolynomialFeaturesÎ°ú Î≥ÄÌôò Îêú Îç∞Ïù¥ÌÑ∞Î•º Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑ ÌòïÌÉúÎ°ú Î≥ÄÌôò

In [22]:
# DecisionTreeClassifier Î™®Îç∏ÏùÑ Î≥ÄÌôòÎêú train Îç∞Ïù¥ÌÑ∞Î°ú ÌïôÏäµ

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(df_poly,train['quality'])

DecisionTreeClassifier()

In [23]:
# test Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò

poly_features = PolynomialFeatures(degree=2) # Ï∞®ÏõêÏùÄ 2Î°ú ÏÑ§Ï†ï

test_poly = poly_features.fit_transform(test) # fit_transform Î©îÏÜåÎìúÎ•º ÌÜµÌï¥ Îç∞Ïù¥ÌÑ∞ Î≥ÄÌôò
test_poly = pd.DataFrame(test_poly) # PolynomialFeaturesÎ°ú Î≥ÄÌôò Îêú Îç∞Ïù¥ÌÑ∞Î•º Îç∞Ïù¥ÌÑ∞ ÌîÑÎ†àÏûÑ ÌòïÌÉúÎ°ú Î≥ÄÌôò

In [24]:
# Í≤∞Í¥èÍ∞í Ï∂îÎ°†
pred = model.predict(test_poly)

In [25]:
# Ï†ïÎãµ ÌååÏùº ÏÉùÏÑ±
submission = pd.read_csv('data/sample_submission.csv')
submission['quality'] = pred
submission.to_csv('poly.csv',index = False)

# [‚Ü©Ô∏è Î¶¨Ïä§Ìä∏Î°ú ÎèåÏïÑÍ∞ÄÍ∏∞](https://dacon.io/competitions/open/235698/overview/description)