<a href="https://colab.research.google.com/github/uvictoli/Machine_Learning/blob/main/Lv4/Lv4_%EC%A0%84%EC%B2%98%EB%A6%AC_6_9_%EC%97%B0%EC%86%8D%ED%98%95_%EB%B3%80%EC%88%98%EB%A5%BC_%EB%B2%94%EC%A3%BC%ED%98%95_%EB%B3%80%EC%88%98%EB%A1%9C_%EB%B0%94%EA%BE%B8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [‚Ü©Ô∏è Î¶¨Ïä§Ìä∏Î°ú ÎèåÏïÑÍ∞ÄÍ∏∞](https://dacon.io/competitions/open/235698/overview/description)

# ÏÖÄÏùÑ Ïã§ÌñâÌï† Îïå ÌåùÏóÖÏù¥ Îú®Î©¥ `Î¨¥ÏãúÌïòÍ≥† Í≥ÑÏÜçÌïòÍ∏∞` Î•º ÎàåÎü¨Ï£ºÏÑ∏Ïöî

## Îç∞Ïù¥ÌÑ∞ Îã§Ïö¥Î°úÎìú
---
ÏïÑÎûò ÏÖÄÏùÑ Ïã§ÌñâÏãúÏºú Îç∞Ïù¥ÌÑ∞Î•º colab Ïóê Î∂àÎü¨ÏòµÎãàÎã§.
ÏÖÄ Ïã§ÌñâÏùÄ Ctrl + Enter Î•º Ïù¥Ïö©Ìï¥ Ïã§ÌñâÏãúÌÇ¨ Ïàò ÏûàÏäµÎãàÎã§.

In [1]:
# Îç∞Ïù¥ÌÑ∞ Îã§Ïö¥Î°úÎìú ÎßÅÌÅ¨Î°ú Îç∞Ïù¥ÌÑ∞Î•º ÏΩîÎû©Ïóê Î∂àÎü¨ÏòµÎãàÎã§.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2022-01-26 09:08:59--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2022-01-26 09:08:59--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 74.125.142.100, 74.125.142.113, 74.125.142.139, ...
Connecting to drive.google.com (drive.google.com)|74.125.142.100|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/c1nb6iraoeqq0prf4cdf0d2b0gtp6fdu/1643188125000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download [following]
Warning: wildcards not supported in HTTP.
--2022-01-26 09:08:59--  https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/c1nb6iraoeqq0prf4cdf0d2b0gtp6fdu/1643188125000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download
Resolving doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)|74.125.195.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137694 (134K) [application/zip]
Saving to: ‚Äò3i4n1QB.4‚Äô

3i4n1QB.4           100%[===================>] 134.47K  --.-KB/s    in 0.001s

2022-01-26 09:08:59 (109 MB/s) - ‚Äò3i4n1QB.4‚Äô saved [137694/137694]

In [2]:
# ÎùºÏù¥Î∏åÎü¨Î¶¨ Î∞è Îç∞Ïù¥ÌÑ∞ Î∂àÎü¨Ïò§Í∏∞
import pandas as pd

train = pd.read_csv('data/train.csv')

## üëã Ïã§Ïäµ
---

In [3]:
# train Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44     10.2  white
1      1        5            8.8  ...       0.59      9.5    red
2      2        5            7.9  ...       0.52     10.9  white
3      3        6            7.0  ...       0.50     10.8  white
4      4        6            7.8  ...       0.43     10.9  white

[5 rows x 14 columns]

In [4]:
# Î∞©Î≤ï1. ÏàòÏπò Î≤îÏúÑ Íµ¨Í∞ÑÏùÑ ÏßÅÏ†ë ÏßÄÏ†ïÌï¥ Î†àÏù¥Î∏îÎßÅ ÌïòÍ∏∞

# train Îç∞Ïù¥ÌÑ∞Ïùò pH Î≥ÄÏàòÎ•º Íµ¨Í∞ÑÏù¥ 4Í∞úÏù∏ Î≤îÏ£ºÌòï Î≥ÄÏàòÎ°ú Î≥ÄÌôò
# pH < 1  -> lowest
# 1<= pH < 2 -> low
# 2 <= pH < 3-> normal
# 3 <= pH -> high
 
def func(x):
  if x < 3: return 'lowest'
  elif x < 3.3: return 'low'
  elif x < 3.5: return 'normal'
  else: return 'high'

train['pH'] = train['pH'].apply(lambda x : func(x))

In [5]:
# Î≥ÄÌôò ÌõÑ Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44     10.2  white
1      1        5            8.8  ...       0.59      9.5    red
2      2        5            7.9  ...       0.52     10.9  white
3      3        6            7.0  ...       0.50     10.8  white
4      4        6            7.8  ...       0.43     10.9  white

[5 rows x 14 columns]

In [6]:
# Î∞©Î≤ï2. pandasÏùò cut() Ìï®ÏàòÎ°ú Î†àÏù¥Î∏îÎßÅ ÌïòÍ∏∞
train['alcohol'] = pd.cut(train.alcohol, 5, labels = False)

In [7]:
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44        1  white
1      1        5            8.8  ...       0.59        1    red
2      2        5            7.9  ...       0.52        2  white
3      3        6            7.0  ...       0.50        2  white
4      4        6            7.8  ...       0.43        2  white

[5 rows x 14 columns]

## Ï†ïÎãµ

In [8]:
# train Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

   index  quality  fixed acidity  ...  sulphates  alcohol   type
0      0        5            5.6  ...       0.44        1  white
1      1        5            8.8  ...       0.59        1    red
2      2        5            7.9  ...       0.52        2  white
3      3        6            7.0  ...       0.50        2  white
4      4        6            7.8  ...       0.43        2  white

[5 rows x 14 columns]

In [9]:
# train Îç∞Ïù¥ÌÑ∞Ïùò pH Î≥ÄÏàòÎ•º Íµ¨Í∞ÑÏù¥ 4Í∞úÏù∏ Î≤îÏ£ºÌòï Î≥ÄÏàòÎ°ú Î≥ÄÌôò
# pH < 1  -> lowest
# 1<= pH < 2 -> low
# 2 <= pH < 3-> normal
# 3 <= pH -> high
 
def func(x):
    if x < 3:
        return 'lowest'
    elif x < 3.3:
        return 'low'
    elif x < 3.5:
        return 'normal'
    else :
        return'high' 

train['pH'] = train['pH'].apply(lambda x : func(x))

TypeError: ignored

In [ ]:
# Î≥ÄÌôò ÌõÑ Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

# [‚Ü©Ô∏è Î¶¨Ïä§Ìä∏Î°ú ÎèåÏïÑÍ∞ÄÍ∏∞](https://dacon.io/competitions/open/235698/overview/description)